In [8]:
my_class=["George","Trifon","Arjun","Jost","Killian","Virginia","Sarah","Lucas","Ottavia","Jaser","Stian","Jess","Arno","Nayab"]

In [9]:
sorted(my_class)

['Arjun',
 'Arno',
 'George',
 'Jaser',
 'Jess',
 'Jost',
 'Killian',
 'Lucas',
 'Nayab',
 'Ottavia',
 'Sarah',
 'Stian',
 'Trifon',
 'Virginia']

In [12]:
my_class.sort()
my_class

['Arjun',
 'Arno',
 'George',
 'Jaser',
 'Jess',
 'Jost',
 'Killian',
 'Lucas',
 'Nayab',
 'Ottavia',
 'Sarah',
 'Stian',
 'Trifon',
 'Virginia']

In [14]:
print(my_class[0])

Arjun


In [21]:
print(my_class[13])

Virginia


In [20]:
for student in my_class:
    print(student)

Arjun
Arno
George
Jaser
Jess
Jost
Killian
Lucas
Nayab
Ottavia
Sarah
Stian
Trifon
Virginia


In [65]:
class_age=[18,43,34,67,32,37,42,38,34,25,27,28,29,33,32,31]
for age in class_age:
    print(age)

18
43
34
67
32
37
42
38
34
25
27
28
29
33
32
31


In [25]:
sorted(class_age)

[18, 25, 27, 28, 29, 31, 32, 32, 33, 34, 34, 37, 38, 42, 43, 67]

In [26]:
class_age.sort()
class_age

[18, 25, 27, 28, 29, 31, 32, 32, 33, 34, 34, 37, 38, 42, 43, 67]

In [48]:
for num in class_age:
     if num % 2 == 0:
        print(num,end=" ")

18 28 32 32 34 34 38 42 

In [60]:
mikos=len(class_age)
mikos

16

In [2]:
class_age=[18,43,34,67,32,37,42,38,34,25,27,28,29,33,32,31]
num=0
while(num<len(class_age)):
    if class_age[num] % 2 == 0:
        print(class_age[num],end=",")
    num +=1


18,34,32,42,38,34,28,32,

In [3]:
numbers_list=[4,54,5,34,62,76,3247,4,5,52,213,8,73434,7,6,54,42,342,54,65,76,8,4,43,6,6,7,8,7,54,547,68,8,86]
numbers_list.sort()
print(numbers_list[0])


4


In [ ]:
numbers_list.sort(reverse=True)
print(numbers_list[0])

73434


In [ ]:
customers_age=[1999, 1995, 2005, 2010, 2007, 2006, 1994, 1996, 1979, 2008]
for age in customers_age:
    print(2022-age)

23
27
17
12
15
16
28
26
43
14


In [ ]:
customers_age=[1999, 1995, 2005, 2010, 2007, 2006, 1994, 1996, 1979, 2008]
i=0
while(i<len(customers_age)):
    print(2022-customers_age[i])
    i+=1
    

23
27
17
12
15
16
28
26
43
14


In [ ]:
customer_list = [
                    {"name": "Bob", "age": 1999},
                    {"name": "Jack", "age": 1995},
                    {"name": "Lisa", "age": 2005},
                    {"name": "Maria", "age": 2010},
                    {"name": "Ben", "age": 2007},
                    {"name": "Emma", "age": 2006},
                    {"name": "Oscar", "age": 1994},
                    {"name": "Amy", "age": 1996},
                    {"name": "Paul", "age": 1979},
                    {"name": "Etta", "age": 2008}
                ]

In [1]:
import numpy as np

In [2]:
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x
# array([[  0,   1,   2,   3,   4],
#        [-99,   6, -99,   8, -99],
#        [-99,  11, -99,  13, -99]])

x.max(axis=1)
# array([ 4,  8, 13])

# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([-0.2049491 ,  1.1972912 , -1.09145895, ..., -1.72843167,
        1.67222596, -0.2209055 ])

In [ ]:
print(customer_list,end=",")

[{'name': 'Bob', 'age': 1999}, {'name': 'Jack', 'age': 1995}, {'name': 'Lisa', 'age': 2005}, {'name': 'Maria', 'age': 2010}, {'name': 'Ben', 'age': 2007}, {'name': 'Emma', 'age': 2006}, {'name': 'Oscar', 'age': 1994}, {'name': 'Amy', 'age': 1996}, {'name': 'Paul', 'age': 1979}, {'name': 'Etta', 'age': 2008}],

In [ ]:
customer_list = [
                    {"name": "Bob", "age": 1999},
                    {"name": "Jack", "age": 1995},
                    {"name": "Lisa", "age": 2005},
                    {"name": "Maria", "age": 2010},
                    {"name": "Ben", "age": 2007},
                    {"name": "Emma", "age": 2006},
                    {"name": "Oscar", "age": 1994},
                    {"name": "Amy", "age": 1996},
                    {"name": "Paul", "age": 1979},
                    {"name": "Etta", "age": 2008}
                ]

      
for i in customer_list:
    print (i['name'],2022-i['age'],"years old")        

Bob 23 years old
Jack 27 years old
Lisa 17 years old
Maria 12 years old
Ben 15 years old
Emma 16 years old
Oscar 28 years old
Amy 26 years old
Paul 43 years old
Etta 14 years old


In [ ]:
ages = [20, 24, 14, 9, 12, 13, 25, 23, 40, 11]
ages.pop(-1)
ages

[20, 24, 14, 9, 12, 13, 25, 23, 40]

In [ ]:
ages = [20, 24, 14, 9, 12, 13, 25, 23, 40, 11]
del ages[0]
print(ages)


[24, 14, 9, 12, 13, 25, 23, 40, 11]


In [ ]:
ages = [20, 24, 14, 9, 12, 13, 25, 23, 40, 11]
ages.pop(-2)
print(ages)
del ages[3]
print(ages)



[20, 24, 14, 9, 12, 13, 25, 23, 11]
[20, 24, 14, 12, 13, 25, 23, 11]


In [1]:
#Exercise 13
berlin = [15, 13, 16, 18, 19, 10, 12 ]
munich = [7, 13, 15, 20, 19, 18, 10, 16]

def common_elements(list1, list2):
    result = []
    for element in list1:
        if element in list2:
            result.append(element)
    return result
    
common_elements(berlin,munich)

[15, 13, 16, 18, 19, 10]

In [5]:
#Exercise 14
mylist=[15,13,16,18,19,15,10]

mylist = list(dict.fromkeys(mylist))
print(mylist)

[15, 13, 16, 18, 19, 10]
